#!/bin/bash

# display a welcome message
function display_welcome(){
	cat /usr/local/bin/.update;
	echo "";
}

function run_apt(){
  # Update the system (APT)
  echo "==> Updating system packages..."
  sudo apt-get full-upgrade

  # Clean orphan packages (APT)
  echo "==> Removing APT orphan packages..."
  sudo apt-get autoremove --purge

  # Clean up package cache (APT)
  echo "==> Cleaning up APT package cache..."
  sudo apt-get autoclean
  sudo apt-get autoremove;
}

function run_pacman(){
  # Update the system (Pacman)
  echo "==> Updating system packages..."
  sudo pacman -Syu

  # Clean orphan packages (Pacman)
  echo "==> Removing Pacman orphan packages..."
  sudo pacman -Rns $(pacman -Qdtq) 2>/dev/null || true
  sudo pacman -Rns $(pacman -Qdtq) 2>/dev/null || true
}

function run_yay(){
  # Update AUR packages (yay)
  echo "==> Updating AUR packages (yay)..."
  yay -Syu --noconfirm

  # Clean orphan packages (yay)
  echo "==> Removing Yay orphan packages..."
  yay -Yc --noconfirm
  yay -Yc --noconfirm
}

function run_update(){
  ### Check if OS is MAC OS - update with brew pkg man
	if [[ "$OSTYPE" == "darwin"* ]]; then
		echo "Running on macOS"

		echo "|--> Updating Brew ...";
		brew update;

		echo "|--> Updating Packages ...";
		brew upgrade;

		exit 0;
	else
		echo "Not running on macOS"
	fi

	### Check if OS is Linux and find the right pkg man to update ###
	if [[ "$OSTYPE" == "linux-gnu"* ]]; then
		
    ## Check if OS is Ubuntu or Debian
    if command -v apt >/dev/null 2>&1; then
			echo "Running Linux with apt installed"
			echo "|--> Updating Packages";
			run_apt;
			exit 0;
		else
			echo "Linux but apt is not installed"
		fi

    ## Check if OS is Arch Linux
    if command -v pacman >/dev/null 2>&1; then
      echo "Running Arch Linux with pacman installed"
      echo "|--> Updating Packages";
      run_pacman;
      exit 0;
    else
      echo "Linux but pacman is not installed"
    fi

    if command -v yay >/dev/null 2>&1; then
      echo "Running Arch Linux with yay installed"
      echo "|--> Updating Packages";
      run_yay;
      exit 0;
    else
      echo "Linux but yay is not installed"
    fi
	
  else
		echo "Not running on Linux"
	fi
}

### MAIN Code entry here ... ###
display_welcome;

echo -n "Do everything (update > upgrade > clean > remove > clean)? (*/N) "
read everything_opt

## Check user input (must be a 'N' to avoid doing everything)
if [ "$everything_opt" == "N" ] || [ "$everything_opt" == "n" ]; then
        echo "Opt-out of everything ..."
	exit 0;
else
	run_update;
fi
